language: generic
sudo: false
os:
- osx
- linux
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        	; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./caskconfig.sh    	; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake compile	; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake test:bintest	; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run bintest 	;fi

