#
# Copyright (c) 2013-2016 by appPlant GmbH. All rights reserved.
#
# @APPPLANT_LICENSE_HEADER_START@
#
# This file contains Original Code and/or Modifications of Original Code
# as defined in and that are subject to the Apache License
# Version 2.0 (the 'License'). You may not use this file except in
# compliance with the License. Please obtain a copy of the License at
# http://opensource.org/licenses/Apache-2.0/ and read it before using this
# file.
#
# The Original Code and all software distributed under the License are
# distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
# EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
# INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
# Please see the License for the specific language governing rights and
# limitations under the License.
#
# @APPPLANT_LICENSE_HEADER_END@

language: go
sudo: false

os:
- osx
- linux

services:
- docker

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh scripts/install.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/install.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . scripts/init.sh; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake compile; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run compile; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake test:bintest; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run bintest; fi

before_deploy:
- docker-compose run release
- export BUILD_VERSION=`rake version`
- sudo chmod -R 1777 releases
- ls -la releases
- ls -la releases/v$BUILD_VERSION

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-i386-apple-darwin14.tgz"
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-i686-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-i686-w64-mingw32.tgz"
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-x86_64-apple-darwin14.tgz"
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
  # - "releases/v$BUILD_VERSION/goo-$BUILD_VERSION.tgz"
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME == linux"

#   slack:
#     secure: ges/NMftobtq3p7FrxFE5xuiN9kYTMC8+tM/ltgZrAxxqvcgygVNqlkBYBf5Z7Q4OFAEjS69/17Kuu1+0VfJZRgNcN70IiXUB5qesVUlR2DtaA+yg4ZXLyEhAnx/gT1aTCooYUhXOtznLk6ts8LjbWMgih9cmgsojZlwqFVBTC3aYh1z7WtuW8hBRXEjSsve9TVGV5keBNqnBUznO9jnCoJOhkESdMzFf/sv9kHmh2UuM/PlWz7yHNt2TpohJh7o5p6dwik5++P0zr3tEe2DY7pYObvWnQOw+i98xVFOUBKakWjprafcqbYw6ZbvC9+BQdTW1rX11E/ExuhMmLZS28ZRBaDK4B7nmJW8dqLbbOQcOg9OJKl49CoLSUZNA3qouvIUvHiamJoIa/7vhEYTY/b593V3gj1C5XNAWZgX6ZXqFhSDEQ2fUavGlBhY5ZIrty1yZReMo5uJXo8LAcSNdxYB1lMhZq2DIyO8Zs8Zbxxt/99lNXLmSDYnLzQDOyfUVozyEWwVf2IYXTMetHLdNLKw2SzhphXmiS8iUgeAyw/DrafMwJUEC0om55Kcs5ruv4HKMOO8I8jKn+naaQeIkXqAHr0ttliKIjHt1ZOeLGYXrO9rMVE028Bhxb0cUlwy2LNe4THCMU4iCsy+pIxtV9H60gajzaGle6balY9n9aQ=
