language: generic
sudo: false
os:
- osx
- linux
services:
- docker
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        	; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./caskconfig.sh    	; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake compile	; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake test:bintest	; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run bintest 	;fi
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose run release	;fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export BUILD_VERSION=`rake local:version`	;fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod -R 1777 releases	;fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la releases			;fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la releases/v$BUILD_VERSION	;fi
notifications:
  slack:
    secure: ges/NMftobtq3p7FrxFE5xuiN9kYTMC8+tM/ltgZrAxxqvcgygVNqlkBYBf5Z7Q4OFAEjS69/17Kuu1+0VfJZRgNcN70IiXUB5qesVUlR2DtaA+yg4ZXLyEhAnx/gT1aTCooYUhXOtznLk6ts8LjbWMgih9cmgsojZlwqFVBTC3aYh1z7WtuW8hBRXEjSsve9TVGV5keBNqnBUznO9jnCoJOhkESdMzFf/sv9kHmh2UuM/PlWz7yHNt2TpohJh7o5p6dwik5++P0zr3tEe2DY7pYObvWnQOw+i98xVFOUBKakWjprafcqbYw6ZbvC9+BQdTW1rX11E/ExuhMmLZS28ZRBaDK4B7nmJW8dqLbbOQcOg9OJKl49CoLSUZNA3qouvIUvHiamJoIa/7vhEYTY/b593V3gj1C5XNAWZgX6ZXqFhSDEQ2fUavGlBhY5ZIrty1yZReMo5uJXo8LAcSNdxYB1lMhZq2DIyO8Zs8Zbxxt/99lNXLmSDYnLzQDOyfUVozyEWwVf2IYXTMetHLdNLKw2SzhphXmiS8iUgeAyw/DrafMwJUEC0om55Kcs5ruv4HKMOO8I8jKn+naaQeIkXqAHr0ttliKIjHt1ZOeLGYXrO9rMVE028Bhxb0cUlwy2LNe4THCMU4iCsy+pIxtV9H60gajzaGle6balY9n9aQ=
deploy:
  provider: releases
  api_key:
    secure: WFsGVFTTSc1o9VuyDKzYvLCn24Sa1c7nntCOUCHTbPvuwan+q6O+B8AGMq6xVmNARMS7hnIGCfBs2he19kkbK0XaKwUmDYi+ABFDD2areKGeOMaq2C9i6eiCPkZNfqZq0xgwTpuzoxOhPg6nuegZntMC2idC/MC9wFbRAEr2HfsRaqitrK/d2Nr54vQ03/MVQbHOJjonQ4zqDtNPjFraGdThOsthR+OfABLq7ct8a2T5glqqXcQxCu1G3Y1AYn3hy8rHoq4gB7BUcsatKyXExLCYBKlXmFMWUrBT66/VtR25Kya7nQ31f6F0k+TVTNF9MM6jkrnqSWqck7UZa9GifIsD1VU7QCn6/o6OcztFi6uLVF0VVm1BIJBv2RTMiqsz3wWdrmiT9kGYF5mHS1QMp2FVYy+GBbgF2Ud9NqWNAepQW5vp3aLx5PJ5y5kTdJSJAKJwIv7IjMQzN3DvtByc8ru+qpPysywYi5xocCgtUek8E1PQdo5If4WEqgRHAd9WWmzMetlq0wPUYP9K2oWYnweax4h5RZxCuux47puvyKcdIDAaHFCctj0+13gWH05/yYvacOobzERKmNYi3eHt6DYBcX2fJ1LKKWGEszj515IKc4kLPU3n/u63mdfMnLeqrC+B7Y6J4tFTj+7pLe0eAnEJGNvUOeTD3ZEXjjulG7s=
  file:
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-i386-apple-darwin14.tgz"
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-i686-pc-linux-gnu.tgz"
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-i686-w64-mingw32.tgz"
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-x86_64-apple-darwin14.tgz"
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
    - "releases/v$BUILD_VERSION/fd-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
    # - "releases/v$BUILD_VERSION/ft-$BUILD_VERSION.tgz"
  skip_cleanup: true
  on:
    tags: true
