version: 0.0.1.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\account\myproject

environment:
  GOPATH: c:\gopath
  matrix:
    - ruby_version: "21"
    - ruby_version: "21-x64"

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - cinst ruby
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-document -v 1.10.5
  - bundle install --retry=3

test_script:
  - bundle exec rake

build: off
