compile: &defaults
  build: .
  volumes:
    - .:/go:rw
  command: rake compile
bintest:
  <<: *defaults
  command: rake test:bintest
clean:
  <<: *defaults
  command: rake clean
release:
  <<: *defaults
  command: rake release
shell:
  <<: *defaults
  command: bash
